################################################################################
# ==> tasks for start-managed-server Role. Starts a managed server using
# ==> nodemanager and waits until the server is up
# ==> author: Christos Vezalis
# ##############################################################################

# ==> Start managed server
- name: Create security folder for managed server
  file: state=directory path={{ domains_home }}/{{ domain_name }}/servers/{{ managed_server_name }}/security
  tags:
    - start-managed-server
- name: Create boot properties file for managed server
  template: src=boot.properties dest={{ domain_home }}/servers/{{ managed_server_name }}/security/
  tags:
    - start-managed-server
- name: Copy Start Managed Server Script
  template: src=start-managed-server.py dest={{ mw_installer_folder }}
  tags:
    - start-managed-server
- name: Start Managed Server
  shell: "{{ weblogic_home }}/common/bin/wlst.sh {{ mw_installer_folder }}/start-managed-server.py"
  ignore_errors: yes
  tags:
    - start-manged-server
- name: Wait for Managed Server to startup 
  wait_for: host={{ server_hostname }} port={{ managed_server_port }} delay=2 timeout=300
  tags:
    - start-managed-server