# ==> Ansible Role for configure, start and autostart on reboot Node manager
# ==> for a WebLogic 12c R2 Domain
- name: Copy Nodemanager Properties file
  template: src=nodemanager.properties dest={{ domain_home }}/nodemanager/ owner={{ oracle_user }} group={{ oracle_group }}
  tags:
    - start-nodemanager

# ==> Create startup script for nodemanager
- name: Copy nodemanager systemd script
  template: src=nodemanager.service dest=/etc/systemd/system/ mode=0664
  tags:
    - start-nodemanager
- name: Enable nodemanager as linux service
  command: 'systemctl enable nodemanager'
  tags:
    - start-nodemanager
- name: Start Node Manager
  command: 'systemctl start nodemanager'
  tags:
    - start-nodemanager
- name: Waiting for nodemanager to come up
  wait_for: port=5556 delay=2 timeout=30
  tags:
    - start-nodemanager